---
title: "Introduction for this COVID app"
output: html_notebook
---

This web site is supporting the work described on [medRxiv (doi.org/10.1101/2020.04.23.20077123)](https://doi.org/10.1101/2020.04.23.20077123)
done by:

1. Danielle Klinger ^1
2. Ido Blass ^1
3. Nadav Rappoport ^2
4. Michal Linial ^1

^[1] The Hebrew University
^[2] Ben-Gurion University

The basic idea is to test whether BCG vaccination regimes in different countries
is associated with different COVID-19 pandemic's oucome.

## Alignment

As different countries were exposed to the virus on different dates, and as
countries differ by population sizes, the first think to do is to align the 
dates of reports.

Alignement can be done based on first date a certain threshold was observed.
For example, the date of first report with more than 0.5 deaths per million.



## Updates
This web sites keeps to be updated and retrieve data on a daily basis. If you 
want to limit the 'available' data to a certain date, chose that date on 
'Latest Date:' button on top. Though the the manuscript results are based on 
results from April 20th, 2020.

## Code availability
This website was build in R Shiny app.

Code for this ShinyApp is available on 
[github.com/nadavrap/COVID19](https://github.com/nadavrap/COVID19).
